### ISSUE TITLE
Setup Menu doesn't display properly on Linux (Mono)

### ISSUE THREAD

**Issue by monstro1** [authorblues/bizhawk-shuffler-2#68]
Tried running the shuffler on the latest Bizhawk version on Linux, and the setup menu looks messed up:
![image](https://github.com/authorblues/bizhawk-shuffler-2/assets/67171463/4ff372ab-b6ef-4084-9709-3b54f2ec34b0)

This error appears in the console:
`NLua.Exceptions.LuaScriptException: ./shuffler-src/setupform.lua:311: bad argument #1 to 'randomseed' (number has no integer representation)`

 - OS: Manjaro Linux
 - Bizhawk Version: 2.9.1

**Comment by kalimag** [comment]
Please test if this version works for you: https://github.com/authorblues/bizhawk-shuffler-2/archive/refs/heads/pr/fix-randomseed.zip

**Comment by kalimag** [comment]
Fixed in 2c8cfa40de05ae01d7e9154814f52812c49be4e0

**Comment by monstro1** [comment]
Still having an issue, albeit a separate one:

The shuffler is attempting to open .bin files (as part of a .bin/.cue pair for ps1 games)

**Comment by kalimag** [comment]
Please open the .cue file in a text editor and compare the file name it contains with the actual file name of the .bin. Do they differ in casing or extension?

I assume the game works if you load the cue manually in BizHawk?
